# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94a244c57d982f8be0ec595b78e66dfd"
name = "lbe"
handle = "lbe"
application_url = "https://lbe.fly.dev/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks/inventory_levels/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_inventory,read_products,read_shipping,write_shipping"

[auth]
redirect_urls = [
  "https://lbe.fly.dev/auth/callback",
  "https://lbe.fly.dev/auth/shopify/callback",
  "https://lbe.fly.dev/api/auth/callback"
]

[pos]
embedded = false
